### ISSUE TITLE
DHL Google maps for servicepoint is always covering checkout

### ISSUE THREAD

**Issue by Krachtstroom** [dhlparcel/plugin-magento2-release#33]
Today, after an update, I discovered that the plugin overlay covers most parts of my checkout. No way a customer can type any credentials. In this way nobody can't use my site.

**Comment by vovayatsyuk** [comment]
I was able to fix this with the following css:

```css
#dhlparcel_shipping_locator_real_reset {
    all: inherit !important;
}
```

This discards `all: initial` styles added by this module:
- https://github.com/dhlparcel/plugin-magento2-release/blob/master/view/frontend/web/css/servicepoint.modal.css#L62-L64
- https://github.com/dhlparcel/plugin-magento2-release/blob/master/view/frontend/web/css/servicepoint.modal.css#L139
